#ifndef PARAMETER_h
#define PARAMETER_h

#define    CALC_WF1_MUL		         1.0
#define    CALC_WF1_ADD		 	 0.0
#define    CALC_WF2_MUL		         1.0
#define    CALC_WF2_ADD                  0.0
#define    CALC_WF3_MUL                  1.0
#define    CALC_WF3_ADD                  0.0
#define    CALC_WF4A_MUL                 0.000343323
#define    CALC_WF4A_ADD                 0.0
#define    CALC_WF4B_MUL                 0.000343323
#define    CALC_WF4B_ADD                 0.0
#define    CALC_WF5A_MUL                 0.000343323
#define    CALC_WF5A_ADD                 0.0
#define    CALC_WF5B_MUL                 0.000343323
#define    CALC_WF5B_ADD                 0.0
#define    CALC_WF6B_MUL                 0.050355
#define    CALC_WF6B_ADD                 0.0
#define    CALC_WF6A_MUL                 0.050355
#define    CALC_WF6A_ADD                 0.0
#define    CALC_WF7_MUL                  0.00038
#define    CALC_WF7_ADD                  0.0
#define    CALC_WF8_MUL                  1.0
#define    CALC_WF8_ADD                  0.0
#define    CALC_WFBPM_MUL                1.0
#define    CALC_WFBPM_ADD                0.0
#define    CALC_WFBPM_PHASE_MUL          0.000343323
#define    CALC_WFBPM_PHASE_ADD          0.0


/* parameter for float value setting */
#define    CALC_Fix_Frequency_Set_MUL           35791394.167
#define    CALC_Fix_Frequency_Set_ADD		0.0
#define    CALC_Work_Period_Set_MUL             60000.0
#define    CALC_Work_Period_Set_ADD		0.0
#define    CALC_AMP_Set_MUL                     438620.0
#define    CALC_AMP_Set_ADD			0.0
#define    CALC_AMP_Coefficient_MUL             1.0
#define    CALC_AMP_Coefficient_ADD		0.0
#define    CALC_AMP_P_Set_MUL                   4096.0
#define    CALC_AMP_P_Set_ADD			0.0
#define    CALC_AMP_I_Set_MUL                   4096.0
#define    CALC_AMP_I_Set_ADD			0.0
#define    CALC_AMP_I_Set1_MUL                  4096.0
#define    CALC_AMP_I_Set1_ADD			0.0
#define    CALC_AMP_I_Set2_MUL                  4096.0
#define    CALC_AMP_I_Set2_ADD			0.0
#define    CALC_AMP_I_Set3_MUL                  4096.0
#define    CALC_AMP_I_Set3_ADD			0.0
#define    CALC_Bias_Set_MUL                    1.0
#define    CALC_Bias_Set_ADD			0.0
#define    CALC_Fix_Tuning_Angle_MUL            2912.7
#define    CALC_Fix_Tuning_Angle_ADD		0.0
#define    CALC_Tuning_Angle_Offset_MUL         2912.7
#define    CALC_Tuning_Angle_Offset_ADD		0.0
#define    CALC_Tune_P_Set_MUL                  4096.0
#define    CALC_Tune_P_Set_ADD			0.0
#define    CALC_Tune_I_Set_MUL                  4096.0
#define    CALC_Tune_I_Set_ADD			0.0
#define    CALC_Tune_I_Set1_MUL                 4096.0
#define    CALC_Tune_I_Set1_ADD			0.0
#define    CALC_Tune_I_Set2_MUL                 4096.0
#define    CALC_Tune_I_Set2_ADD			0.0
#define    CALC_Tune_I_Set3_MUL                 4096.0
#define    CALC_Tune_I_Set3_ADD			0.0
#define    CALC_Front_Bias_Set_MUL              1.0
#define    CALC_Front_Bias_Set_ADD		0.0
#define    CALC_Front_Tune_P_Set_MUL            4096.0
#define    CALC_Front_Tune_P_Set_ADD		0.0
#define    CALC_Front_Tune_I_Set_MUL            4096.0
#define    CALC_Front_Tune_I_Set_ADD		0.0
#define    CALC_Front_Fix_Tuning_Angle_MUL      2912.7
#define    CALC_Front_Fix_Tuning_Angle_ADD	0.0
#define    CALC_PHASE_I_MUL    			4096.0
#define    CALC_PHASE_I_ADD			0.0
#define    CALC_PHASE_P_MUL    			4096.0
#define    CALC_PHASE_P_ADD			0.0
#define    CALC_INITIAL_PHASE_MUL    		2912.7
#define    CALC_INITIAL_PHASE_ADD		0.0
#define    CALC_FF_DELAY_MUL    		1.0
#define    CALC_FF_DELAY_ADD			0.0
#define    CALC_PreTrig_Delay_MUL    		1.0
#define    CALC_PreTrig_Delay_ADD		0.0
#define    CALC_Initial_Ref_Phase_MUL  		2912.7
#define    CALC_Initial_Ref_Phase_ADD		0.0
#define	   CALC_Int_Delay_ADD			0.0
#define	   CALC_Int_Delay_MUL			60000.0
#define    CALC_ARC_COUNT_MUL    		1.0
#define    CALC_ARC_COUNT_ADD			0.0
#define	   CALC_CHOPPER_DUTY_ADD		1048572
#define	   CALC_CHOPPER_DUTY_MUL		10485.72
#define	   CALC_RF_HARMONIC_ADD			0.0
#define	   CALC_RF_HARMONIC_MUL			1.0
#define	   CALC_EX_Phase_MUL			2912.7
#define	   CALC_EX_Phase_ADD			0.0
#define	   CALC_CHOPPER_Phase_MUL		2912.7
#define	   CALC_CHOPPER_Phase_ADD		0.0
#define    CALC_REF_DELAY_C_ADD			0.0
#define	   CALC_REF_DELAY_C_MUL			1.0
#define    CALC_REF_DELAY_AB_ADD		0.0
#define	   CALC_REF_DELAY_AB_MUL		1.0
#define    CALC_REF_DELAY_D_ADD			0.0
#define	   CALC_REF_DELAY_D_MUL			1.0
#define    CALC_BEAM_FF_DELAY_ADD		0.0
#define	   CALC_BEAM_FF_DELAY_MUL		1.0
#define    CALC_INJ_PHASE_I_MUL   		4096.0
#define    CALC_INJ_PHASE_I_ADD			0.0
#define	   CALC_Syn_Osc_Delay_MUL		1.0
#define    CALC_Syn_Osc_Delay_ADD		0
#define	   CALC_Syn_Osc_Count_MUL		1.0
#define    CALC_Syn_Osc_Count_ADD		0

#endif  /*end of PARAMETER_h*/
