TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
DB += rcsRfGl.db
DB += rcsRf1.db
DB += rcsRf2.db
DB += rcsRf3.db
DB += rcsRf4.db
DB += rcsRf5.db
DB += rcsRf6.db
DB += rcsRf7.db
DB += rcsRf8.db
DB += rcsRf9.db
DB += calcPV.db
#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

